/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sorteador;

import java.awt.Color;
import java.util.Arrays;

/**
 *
 * @author Allan
 */
public class sorteadorMegaSena extends javax.swing.JFrame {

    /**
     * Creates new form sorteadorMegaSena
     */
    public sorteadorMegaSena() {
        Color cor = new Color(0, 124, 23);
        initComponents();
        panResposta.setVisible(false);
        getContentPane().setBackground(cor);
        panResposta.setBackground(cor);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    private void sorteio(){
      int megaSena[] = new int [6];
      Double random;      
     for(int i=0;i<6;i++){
        random = 1 + Math.random()* (60-1);
     megaSena[i] = random.intValue();
     }
    
     /*Percorre o vetor e compara os valores(exceto a mesma posição),caso os valores forem iguais sorteia outro 
     numero*/
     for(int a=0;a<6;a++){
         for(int b=0;b<6;b++){
             if(a==b){
             
             }else{
                 if(megaSena[a]== megaSena[b]){
                   random = 1 + Math.random()* (60-1);
                   megaSena[a] = random.intValue();
                 }
             }
             
         }
     }
      Arrays.sort(megaSena);
      lbResultado.setText(Integer.toString(megaSena[0]));
      lbResultado2.setText(Integer.toString(megaSena[1]));
      lbResultado3.setText(Integer.toString(megaSena[2]));
      lbResultado4.setText(Integer.toString(megaSena[3]));
      lbResultado5.setText(Integer.toString(megaSena[4]));
      lbResultado6.setText(Integer.toString(megaSena[5]));
    }
    
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btSortear = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        panResposta = new javax.swing.JPanel();
        lbResultado = new javax.swing.JLabel();
        lbResultado2 = new javax.swing.JLabel();
        lbResultado3 = new javax.swing.JLabel();
        lbResultado4 = new javax.swing.JLabel();
        lbResultado5 = new javax.swing.JLabel();
        lbResultado6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btSortear.setText("Sortear");
        btSortear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSortearActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Sorteador de Numeros da Mega Sena");

        lbResultado.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        lbResultado.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbResultado.setText("0");

        lbResultado2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        lbResultado2.setText("1");

        lbResultado3.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        lbResultado3.setText("2");

        lbResultado4.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        lbResultado4.setText("3");

        lbResultado5.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        lbResultado5.setText("4");

        lbResultado6.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        lbResultado6.setText("5");

        javax.swing.GroupLayout panRespostaLayout = new javax.swing.GroupLayout(panResposta);
        panResposta.setLayout(panRespostaLayout);
        panRespostaLayout.setHorizontalGroup(
            panRespostaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panRespostaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panRespostaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panRespostaLayout.createSequentialGroup()
                        .addGroup(panRespostaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbResultado2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbResultado3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panRespostaLayout.createSequentialGroup()
                        .addGroup(panRespostaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbResultado5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbResultado6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbResultado4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        panRespostaLayout.setVerticalGroup(
            panRespostaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panRespostaLayout.createSequentialGroup()
                .addComponent(lbResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbResultado2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbResultado3, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbResultado4)
                .addGap(3, 3, 3)
                .addComponent(lbResultado5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbResultado6)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(btSortear)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
            .addComponent(panResposta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(40, 40, 40)
                .addComponent(btSortear)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panResposta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSortearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSortearActionPerformed
       
      sorteio();
      panResposta.setVisible(true);
    }//GEN-LAST:event_btSortearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(sorteadorMegaSena.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(sorteadorMegaSena.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(sorteadorMegaSena.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(sorteadorMegaSena.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new sorteadorMegaSena().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btSortear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbResultado;
    private javax.swing.JLabel lbResultado2;
    private javax.swing.JLabel lbResultado3;
    private javax.swing.JLabel lbResultado4;
    private javax.swing.JLabel lbResultado5;
    private javax.swing.JLabel lbResultado6;
    private javax.swing.JPanel panResposta;
    // End of variables declaration//GEN-END:variables
}
